CREATE DATABASE SQL
USE SQL


CREATE TABLE ROLES
(
ID INT IDENTITY PRIMARY KEY,
[NAME] NVARCHAR(256)NOT NULL UNIQUE
)


CREATE TABLE USERS
(
ID INT IDENTITY PRIMARY KEY,
USERNAME NVARCHAR(64)NOT NULL UNIQUE,
[PASSWORD] NVARCHAR(64)NOT NULL,
ROLESID INT CONSTRAINT FK_ROLES FOREIGN KEY REFERENCES ROLES(ID)
)


INSERT INTO USERS VALUES
('RAUF041','RAUF012',1),
('IBRAHIM12','IBRAHIM21',2),
('KAMIL02','KAMIL20',3)


SELECT U.USERNAME AS USERNAME, R.[NAME] AS ROLE FROM USERS AS U
LEFT JOIN ROLES AS R
ON U.ROLESID=R.ID



--TASK2


CREATE TABLE CATEGORIES
(
ID INT IDENTITY PRIMARY KEY,
[NAME] NVARCHAR(64)NOT NULL UNIQUE,
)


CREATE TABLE PRODUCTS
(
ID INT IDENTITY PRIMARY KEY,
[NAME] NVARCHAR(64)NOT NULL UNIQUE,
PRICE DECIMAL (4,1),
COST DECIMAL (4,1),
CATEGORYID INT NOT NULL CONSTRAINT FK_PRODUCT FOREIGN KEY REFERENCES PRODUCTS(ID)
)



CREATE TABLE SIZES
(
ID INT IDENTITY PRIMARY KEY,
[NAME] NVARCHAR(64)NOT NULL UNIQUE,
)


CREATE TABLE PRODUCTSIZE
(
ID INT IDENTITY PRIMARY KEY,
PRODUCTID INT NOT NULL CONSTRAINT FK_PROD FOREIGN KEY REFERENCES PRODUCTS(ID),
SIZEID INT NOT NULL CONSTRAINT FK_SIZE FOREIGN KEY REFERENCES SIZES(ID)
)


INSERT INTO CATEGORIES VALUES
('CAR'),
('PLANE'),
('MOTO'),
('BUS'),
('SHIP')


INSERT INTO PRODUCTS VALUES
('TESLA', 10000,1000,1),
('AZERLINE',500000,5000,2),
('FERRARI',10006,1006,3),
('BAKUBUS',30000,3000,4)


INSERT INTO SIZES VALUES
(12),(13),(14),(15),(16)

INSERT INTO PRODUCTSIZE VALUES
(1,1),(1,2),(2,1),(2,3),(3,2)

SELECT PRODUCTS.[NAME] AS PRODUCTNAME,
CATEGORIES.[NAME] AS CATEGORYNAME,
SIZES.[NAME] AS SIZENAME
FROM PRODUCTS
INNER JOIN CATEGORIES ON PRODUCTS.CATEGORYID = CATEGORIES.ID
INNER JOIN PRODUCTSIZE ON PRODUCTS.ID = PRODUCTSIZE.PRODUCTID
INNER JOIN SIZES ON PRODUCTSIZE.SIZEID = SIZES.ID;
